[versions]
kotlin = "1.9.22"
androidGradle = "8.2.2"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
application = { id = "com.android.application", version.ref = "androidGradle" }
library = { id = "com.android.library", version.ref = "androidGradle" }
androidGradleX = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
resourcePlaceholders = "pt.jcosta.resourceplaceholders:0.11.0"